services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.25.3
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
      BASE_URL: /
      PERSIST_AUTHORIZATION: true
    volumes:
      - ./spec/openapi.yaml:/app/openapi.yaml:ro
