artifactUrl: https://ubill.ge
artifactVersion: 0.1.1
composerPackageName: ubill/sdk
developerOrganization: ABGEO
developerOrganizationUrl: https://www.abgeo.dev
invokerPackage: UBill\Sdk
licenseName: MIT
packageName: sdk-php
srcBasePath: src
variableNamingConvention: camelCase

files:
  .github/CODEOWNERS: { }
  .github/release-drafter.yaml: { }
  .github/workflows/release-drafter.yaml: { }
  CONTRIBUTING.md: { }
  LICENSE: { }
  .github/workflows/test-and-lint.yaml: { }
