apiPackage: api
axiosVersion: ^1.9.0
licenseName: MIT
modelPackage: model
npmName: '@ubill/sdk'
npmVersion: 0.1.2
supportsES6: true
useSingleRequestParameter: true
withInterfaces: true
withNodeImports: true
withSeparateModelsAndApi: true

files:
  .github/CODEOWNERS: { }
  .github/release-drafter.yaml: { }
  .github/workflows/release-drafter.yaml: { }
  CONTRIBUTING.md: { }
  LICENSE: { }
  .github/workflows/lint.yaml: { }
  .github/workflows/publish.yaml: { }
  eslint.config.mjs: { }
