name: Run Linter

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Spectral Linter
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'spec/*'
